#ifndef BEOREMOTE_ONE_TYPES_H_
#define BEOREMOTE_ONE_TYPES_H_

#include <stddef.h>
#include <stdint.h>

#define BEOREMOTE_ONE_CONNECTED_MAX 8
#define BEOREMOTE_ONE_ATTRIB_MAX_SIZE 512
#define BEOREMOTE_ONE_SOCKET_MSG_HEADER_SIZE 3
#define BEOREMOTE_ONE_SOCKET_PATH "/var/run/beoremote_one_socket"

enum beoremote_one_attrib {
    BEOREMOTE_ONE_ATTRIB_VERSION = 1,
    BEOREMOTE_ONE_ATTRIB_FEATURES,
    BEOREMOTE_ONE_ATTRIB_FEATURES_CHANGED,
    BEOREMOTE_ONE_ATTRIB_INJECT_PRESS,
    BEOREMOTE_ONE_ATTRIB_INJECT_RELEASE,
    BEOREMOTE_ONE_ATTRIB_DISC_TRACK,
    BEOREMOTE_ONE_ATTRIB_STAND_POSITIONS,
    BEOREMOTE_ONE_ATTRIB_ACTIVE_STAND_POSITION,
    BEOREMOTE_ONE_ATTRIB_SPEAKER_GROUPS,
    BEOREMOTE_ONE_ATTRIB_ACTIVE_SPEAKER_GROUP,
    BEOREMOTE_ONE_ATTRIB_SOUND_MODES,
    BEOREMOTE_ONE_ATTRIB_ACTIVE_SOUND_MODE,
    BEOREMOTE_ONE_ATTRIB_PICTURE_FORMATS,
    BEOREMOTE_ONE_ATTRIB_ACTIVE_PICTURE_FORMAT,
    BEOREMOTE_ONE_ATTRIB_PICTURE_MODES,
    BEOREMOTE_ONE_ATTRIB_ACTIVE_PICTURE_MODE,
    BEOREMOTE_ONE_ATTRIB_PICTURE_MUTE,
    BEOREMOTE_ONE_ATTRIB_2D_3D_MODES,
    BEOREMOTE_ONE_ATTRIB_ACTIVE_2D_3D_MODE,
    BEOREMOTE_ONE_ATTRIB_TV_SOURCES,
    BEOREMOTE_ONE_ATTRIB_MUSIC_SOURCES,
    BEOREMOTE_ONE_ATTRIB_ACTIVE_SOURCE,
    BEOREMOTE_ONE_ATTRIB_CUSTOM_COMMANDS,
    BEOREMOTE_ONE_ATTRIB_ACTIVE_CUSTOM_COMMAND,
    BEOREMOTE_ONE_ATTRIB_HOME_CONTROL_SCENES,
    BEOREMOTE_ONE_ATTRIB_ACTIVE_HOME_CONTROL_SCENE,
    BEOREMOTE_ONE_ATTRIB_CINEMA_MODE,
    BEOREMOTE_ONE_ATTRIB_EXPERIENCES,
    BEOREMOTE_ONE_ATTRIB_ACTIVE_EXPERIENCE,
    BEOREMOTE_ONE_ATTRIB_CONTROL_1,
    BEOREMOTE_ONE_ATTRIB_CONTROL_2,
    BEOREMOTE_ONE_ATTRIB_SOURCE_CONTENT_1,
    BEOREMOTE_ONE_ATTRIB_SOURCE_CONTENT_2,
    BEOREMOTE_ONE_ATTRIB_SOURCE_CONTENT_3,
    BEOREMOTE_ONE_ATTRIB_SOURCE_CONTENT_4,
    BEOREMOTE_ONE_ATTRIB_SOURCE_CONTENT_5,
    BEOREMOTE_ONE_ATTRIB_SOURCE_CONTENT_6,
    BEOREMOTE_ONE_ATTRIB_SOURCE_CONTENT_7,
    BEOREMOTE_ONE_ATTRIB_SOURCE_CONTENT_8,
    BEOREMOTE_ONE_ATTRIB_SOURCE_CONTENT_9,
    BEOREMOTE_ONE_ATTRIB_SOURCE_CONTENT_10,
    BEOREMOTE_ONE_ATTRIB_ACTIVE_SOURCE_CONTENT,
    BEOREMOTE_ONE_ATTRIB_MY_BUTTONS,
    BEOREMOTE_ONE_ATTRIB_VOLUME,

    /* Must be the last item! */
    BEOREMOTE_ONE_ATTRIB_MAX
};

#ifdef __cplusplus
extern "C" {
#endif

size_t beoremote_one_attrib_size(enum beoremote_one_attrib attrib);

const char *beoremote_one_attrib_to_string(enum beoremote_one_attrib attrib);

char *beoremote_one_attrib_data_to_string(enum beoremote_one_attrib, const uint8_t *, size_t, char *, size_t);

#ifdef __cplusplus
}
#endif

#endif /* BEOREMOTE_ONE_TYPES_H_ */
