/* valatyperegisterfunction.c generated by valac, the Vala compiler
 * generated from valatyperegisterfunction.vala, do not modify */

/* valatyperegisterfunction.vala
 *
 * Copyright (C) 2006-2010  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */


#include <glib.h>
#include <glib-object.h>
#include "valacodegen.h"
#include <valaccode.h>
#include <vala.h>
#include <stdlib.h>
#include <string.h>
#include <valagee.h>
#include <gobject/gvaluecollector.h>

#define _vala_ccode_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_ccode_node_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
typedef struct _ValaParamSpecTypeRegisterFunction ValaParamSpecTypeRegisterFunction;

struct _ValaTypeRegisterFunctionPrivate {
	ValaCCodeFragment* source_declaration_fragment;
	ValaCCodeFragment* declaration_fragment;
	ValaCCodeFragment* definition_fragment;
};

struct _ValaParamSpecTypeRegisterFunction {
	GParamSpec parent_instance;
};


static gint ValaTypeRegisterFunction_private_offset;
static gpointer vala_typeregister_function_parent_class = NULL;

static ValaTypeSymbol* vala_typeregister_function_real_get_type_declaration (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_type_struct_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_base_init_func_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_class_finalize_func_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_base_finalize_func_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_class_init_func_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_instance_struct_size (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_instance_init_func_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_parent_type_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_gtype_value_table_init_function_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_gtype_value_table_peek_pointer_function_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_gtype_value_table_free_function_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_gtype_value_table_copy_function_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_gtype_value_table_lcopy_value_function_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_gtype_value_table_collect_value_function_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_type_flags (ValaTypeRegisterFunction* self);
static ValaCCodeFragment* vala_typeregister_function_real_get_type_interface_init_declaration (ValaTypeRegisterFunction* self);
static void vala_typeregister_function_real_get_type_interface_init_statements (ValaTypeRegisterFunction* self,
                                                                         ValaCodeContext* context,
                                                                         ValaCCodeBlock* block,
                                                                         gboolean plugin);
static ValaSymbolAccessibility vala_typeregister_function_real_get_accessibility (ValaTypeRegisterFunction* self);
static void vala_typeregister_function_finalize (ValaTypeRegisterFunction * obj);


static inline gpointer
vala_typeregister_function_get_instance_private (ValaTypeRegisterFunction* self)
{
	return G_STRUCT_MEMBER_P (self, ValaTypeRegisterFunction_private_offset);
}


/**
 * Constructs the C function from the specified type.
 */
static gpointer
_vala_code_node_ref0 (gpointer self)
{
	return self ? vala_code_node_ref (self) : NULL;
}


static gpointer
_vala_ccode_node_ref0 (gpointer self)
{
	return self ? vala_ccode_node_ref (self) : NULL;
}


void
vala_typeregister_function_init_from_type (ValaTypeRegisterFunction* self,
                                           ValaCodeContext* context,
                                           gboolean plugin,
                                           gboolean declaration_only)
{
	ValaTypeSymbol* type_symbol = NULL;
	ValaTypeSymbol* _tmp0_;
	gboolean use_thread_safe = FALSE;
	gboolean fundamental = FALSE;
	ValaClass* cl = NULL;
	ValaTypeSymbol* _tmp1_;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	ValaClass* _tmp4_;
	gchar* type_id_name = NULL;
	ValaTypeSymbol* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	ValaCCodeBlock* type_block = NULL;
	ValaCCodeBlock* _tmp16_;
	ValaCCodeDeclaration* _cdecl_ = NULL;
	gboolean _tmp17_;
	ValaCCodeDeclaration* _tmp34_;
	gboolean _tmp35_;
	ValaCCodeFunction* fun = NULL;
	gchar* type_value_table_decl_name = NULL;
	ValaCCodeBlock* type_init = NULL;
	ValaCCodeBlock* _tmp104_;
	gboolean _tmp105_;
	ValaTypeSymbol* _tmp131_;
	ValaCCodeBlock* _tmp169_;
	ValaCCodeFragment* _tmp170_;
	ValaCCodeFragment* _tmp171_;
	ValaCCodeFunctionCall* reg_call = NULL;
	ValaTypeSymbol* _tmp172_;
	ValaCCodeFunctionCall* _tmp215_;
	ValaTypeSymbol* _tmp216_;
	gchar* _tmp217_;
	gchar* _tmp218_;
	gchar* _tmp219_;
	gchar* _tmp220_;
	ValaCCodeConstant* _tmp221_;
	ValaCCodeConstant* _tmp222_;
	ValaTypeSymbol* _tmp223_;
	gboolean _tmp320_ = FALSE;
	gboolean _tmp321_;
	gboolean _tmp339_ = FALSE;
	ValaClass* _tmp340_;
	gboolean _tmp364_ = FALSE;
	ValaClass* _tmp365_;
	gboolean _tmp479_;
	ValaCCodeFunction* _tmp494_;
	ValaCCodeBlock* _tmp495_;
	ValaCCodeFragment* _tmp496_;
	ValaCCodeFunction* _tmp497_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	_tmp0_ = vala_typeregister_function_get_type_declaration (self);
	type_symbol = _tmp0_;
	use_thread_safe = !plugin;
	fundamental = FALSE;
	_tmp1_ = type_symbol;
	cl = G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, VALA_TYPE_CLASS) ? ((ValaClass*) _tmp1_) : NULL;
	_tmp4_ = cl;
	if (_tmp4_ != NULL) {
		ValaClass* _tmp5_;
		gboolean _tmp6_;
		gboolean _tmp7_;
		_tmp5_ = cl;
		_tmp6_ = vala_class_get_is_compact (_tmp5_);
		_tmp7_ = _tmp6_;
		_tmp3_ = !_tmp7_;
	} else {
		_tmp3_ = FALSE;
	}
	if (_tmp3_) {
		ValaClass* _tmp8_;
		ValaClass* _tmp9_;
		ValaClass* _tmp10_;
		_tmp8_ = cl;
		_tmp9_ = vala_class_get_base_class (_tmp8_);
		_tmp10_ = _tmp9_;
		_tmp2_ = _tmp10_ == NULL;
	} else {
		_tmp2_ = FALSE;
	}
	if (_tmp2_) {
		fundamental = TRUE;
	}
	_tmp11_ = type_symbol;
	_tmp12_ = vala_get_ccode_lower_case_name ((ValaCodeNode*) _tmp11_, NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_strdup_printf ("%s_type_id", _tmp13_);
	_tmp15_ = _tmp14_;
	_g_free0 (_tmp13_);
	type_id_name = _tmp15_;
	_tmp16_ = vala_ccode_block_new ();
	type_block = _tmp16_;
	_tmp17_ = use_thread_safe;
	if (_tmp17_) {
		ValaCCodeDeclaration* _tmp18_;
		ValaCCodeDeclaration* _tmp19_;
		const gchar* _tmp20_;
		gchar* _tmp21_;
		gchar* _tmp22_;
		ValaCCodeConstant* _tmp23_;
		ValaCCodeConstant* _tmp24_;
		ValaCCodeVariableDeclarator* _tmp25_;
		ValaCCodeVariableDeclarator* _tmp26_;
		_tmp18_ = vala_ccode_declaration_new ("gsize");
		_vala_ccode_node_unref0 (_cdecl_);
		_cdecl_ = _tmp18_;
		_tmp19_ = _cdecl_;
		_tmp20_ = type_id_name;
		_tmp21_ = g_strconcat (_tmp20_, "__volatile", NULL);
		_tmp22_ = _tmp21_;
		_tmp23_ = vala_ccode_constant_new ("0");
		_tmp24_ = _tmp23_;
		_tmp25_ = vala_ccode_variable_declarator_new (_tmp22_, (ValaCCodeExpression*) _tmp24_, NULL);
		_tmp26_ = _tmp25_;
		vala_ccode_declaration_add_declarator (_tmp19_, (ValaCCodeDeclarator*) _tmp26_);
		_vala_ccode_node_unref0 (_tmp26_);
		_vala_ccode_node_unref0 (_tmp24_);
		_g_free0 (_tmp22_);
	} else {
		ValaCCodeDeclaration* _tmp27_;
		ValaCCodeDeclaration* _tmp28_;
		const gchar* _tmp29_;
		ValaCCodeConstant* _tmp30_;
		ValaCCodeConstant* _tmp31_;
		ValaCCodeVariableDeclarator* _tmp32_;
		ValaCCodeVariableDeclarator* _tmp33_;
		_tmp27_ = vala_ccode_declaration_new ("GType");
		_vala_ccode_node_unref0 (_cdecl_);
		_cdecl_ = _tmp27_;
		_tmp28_ = _cdecl_;
		_tmp29_ = type_id_name;
		_tmp30_ = vala_ccode_constant_new ("0");
		_tmp31_ = _tmp30_;
		_tmp32_ = vala_ccode_variable_declarator_new (_tmp29_, (ValaCCodeExpression*) _tmp31_, NULL);
		_tmp33_ = _tmp32_;
		vala_ccode_declaration_add_declarator (_tmp28_, (ValaCCodeDeclarator*) _tmp33_);
		_vala_ccode_node_unref0 (_tmp33_);
		_vala_ccode_node_unref0 (_tmp31_);
	}
	_tmp34_ = _cdecl_;
	vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp34_, VALA_CCODE_MODIFIERS_STATIC);
	_tmp35_ = use_thread_safe;
	if (_tmp35_) {
		ValaCCodeDeclaration* _tmp36_;
		ValaCCodeDeclaration* _tmp37_;
		ValaCCodeModifiers _tmp38_;
		ValaCCodeModifiers _tmp39_;
		_tmp36_ = _cdecl_;
		_tmp37_ = _cdecl_;
		_tmp38_ = vala_ccode_node_get_modifiers ((ValaCCodeNode*) _tmp37_);
		_tmp39_ = _tmp38_;
		vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp37_, _tmp39_ | VALA_CCODE_MODIFIERS_VOLATILE);
	}
	if (!plugin) {
		ValaCCodeBlock* _tmp40_;
		ValaCCodeDeclaration* _tmp41_;
		_tmp40_ = type_block;
		_tmp41_ = _cdecl_;
		vala_ccode_block_add_statement (_tmp40_, (ValaCCodeNode*) _tmp41_);
	} else {
		ValaCCodeFragment* _tmp42_;
		ValaCCodeDeclaration* _tmp43_;
		_tmp42_ = self->priv->source_declaration_fragment;
		_tmp43_ = _cdecl_;
		vala_ccode_fragment_append (_tmp42_, (ValaCCodeNode*) _tmp43_);
	}
	if (!plugin) {
		ValaTypeSymbol* _tmp44_;
		gchar* _tmp45_;
		gchar* _tmp46_;
		gchar* _tmp47_;
		gchar* _tmp48_;
		ValaCCodeFunction* _tmp49_;
		ValaCCodeFunction* _tmp50_;
		ValaCCodeFunction* _tmp62_;
		ValaCCodeFragment* _tmp63_;
		ValaCCodeFunction* _tmp64_;
		ValaCCodeFunction* _tmp65_;
		ValaCCodeFunction* _tmp66_;
		ValaCCodeFunction* _tmp67_;
		_tmp44_ = type_symbol;
		_tmp45_ = vala_get_ccode_lower_case_name ((ValaCodeNode*) _tmp44_, NULL);
		_tmp46_ = _tmp45_;
		_tmp47_ = g_strdup_printf ("%s_get_type", _tmp46_);
		_tmp48_ = _tmp47_;
		_tmp49_ = vala_ccode_function_new (_tmp48_, "GType");
		_vala_ccode_node_unref0 (fun);
		fun = _tmp49_;
		_g_free0 (_tmp48_);
		_g_free0 (_tmp46_);
		_tmp50_ = fun;
		vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp50_, VALA_CCODE_MODIFIERS_CONST);
		if (vala_typeregister_function_get_accessibility (self) == VALA_SYMBOL_ACCESSIBILITY_PRIVATE) {
			ValaCCodeFunction* _tmp51_;
			ValaCCodeFunction* _tmp52_;
			ValaCCodeModifiers _tmp53_;
			ValaCCodeModifiers _tmp54_;
			_tmp51_ = fun;
			_tmp52_ = fun;
			_tmp53_ = vala_ccode_node_get_modifiers ((ValaCCodeNode*) _tmp52_);
			_tmp54_ = _tmp53_;
			vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp52_, _tmp54_ | (VALA_CCODE_MODIFIERS_STATIC | VALA_CCODE_MODIFIERS_UNUSED));
		} else {
			gboolean _tmp55_ = FALSE;
			gboolean _tmp56_;
			gboolean _tmp57_;
			_tmp56_ = vala_code_context_get_hide_internal (context);
			_tmp57_ = _tmp56_;
			if (_tmp57_) {
				_tmp55_ = vala_typeregister_function_get_accessibility (self) == VALA_SYMBOL_ACCESSIBILITY_INTERNAL;
			} else {
				_tmp55_ = FALSE;
			}
			if (_tmp55_) {
				ValaCCodeFunction* _tmp58_;
				ValaCCodeFunction* _tmp59_;
				ValaCCodeModifiers _tmp60_;
				ValaCCodeModifiers _tmp61_;
				_tmp58_ = fun;
				_tmp59_ = fun;
				_tmp60_ = vala_ccode_node_get_modifiers ((ValaCCodeNode*) _tmp59_);
				_tmp61_ = _tmp60_;
				vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp59_, _tmp61_ | (VALA_CCODE_MODIFIERS_INTERNAL | VALA_CCODE_MODIFIERS_UNUSED));
			}
		}
		_tmp62_ = fun;
		vala_ccode_function_set_is_declaration (_tmp62_, TRUE);
		_tmp63_ = self->priv->declaration_fragment;
		_tmp64_ = fun;
		_tmp65_ = vala_ccode_function_copy (_tmp64_);
		_tmp66_ = _tmp65_;
		vala_ccode_fragment_append (_tmp63_, (ValaCCodeNode*) _tmp66_);
		_vala_ccode_node_unref0 (_tmp66_);
		_tmp67_ = fun;
		vala_ccode_function_set_is_declaration (_tmp67_, FALSE);
	} else {
		ValaTypeSymbol* _tmp68_;
		gchar* _tmp69_;
		gchar* _tmp70_;
		gchar* _tmp71_;
		gchar* _tmp72_;
		ValaCCodeFunction* _tmp73_;
		ValaCCodeFunction* _tmp74_;
		ValaCCodeParameter* _tmp75_;
		ValaCCodeParameter* _tmp76_;
		ValaCCodeFunction* get_fun = NULL;
		ValaTypeSymbol* _tmp77_;
		gchar* _tmp78_;
		gchar* _tmp79_;
		gchar* _tmp80_;
		gchar* _tmp81_;
		ValaCCodeFunction* _tmp82_;
		ValaCCodeFunction* _tmp83_;
		ValaCCodeFunction* _tmp84_;
		ValaCCodeFunction* _tmp85_;
		ValaCCodeFragment* _tmp86_;
		ValaCCodeFunction* _tmp87_;
		ValaCCodeFunction* _tmp88_;
		ValaCCodeFunction* _tmp89_;
		ValaCCodeFunction* _tmp90_;
		ValaCCodeFunction* _tmp91_;
		ValaCCodeBlock* _tmp92_;
		ValaCCodeBlock* _tmp93_;
		ValaCCodeFunction* _tmp94_;
		ValaCCodeBlock* _tmp95_;
		ValaCCodeBlock* _tmp96_;
		const gchar* _tmp97_;
		ValaCCodeIdentifier* _tmp98_;
		ValaCCodeIdentifier* _tmp99_;
		ValaCCodeReturnStatement* _tmp100_;
		ValaCCodeReturnStatement* _tmp101_;
		ValaCCodeFragment* _tmp102_;
		ValaCCodeFunction* _tmp103_;
		_tmp68_ = type_symbol;
		_tmp69_ = vala_get_ccode_lower_case_name ((ValaCodeNode*) _tmp68_, NULL);
		_tmp70_ = _tmp69_;
		_tmp71_ = g_strdup_printf ("%s_register_type", _tmp70_);
		_tmp72_ = _tmp71_;
		_tmp73_ = vala_ccode_function_new (_tmp72_, "GType");
		_vala_ccode_node_unref0 (fun);
		fun = _tmp73_;
		_g_free0 (_tmp72_);
		_g_free0 (_tmp70_);
		_tmp74_ = fun;
		_tmp75_ = vala_ccode_parameter_new ("module", "GTypeModule *");
		_tmp76_ = _tmp75_;
		vala_ccode_function_add_parameter (_tmp74_, _tmp76_);
		_vala_ccode_node_unref0 (_tmp76_);
		_tmp77_ = type_symbol;
		_tmp78_ = vala_get_ccode_lower_case_name ((ValaCodeNode*) _tmp77_, NULL);
		_tmp79_ = _tmp78_;
		_tmp80_ = g_strdup_printf ("%s_get_type", _tmp79_);
		_tmp81_ = _tmp80_;
		_tmp82_ = vala_ccode_function_new (_tmp81_, "GType");
		_tmp83_ = _tmp82_;
		_g_free0 (_tmp81_);
		_g_free0 (_tmp79_);
		get_fun = _tmp83_;
		_tmp84_ = get_fun;
		vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp84_, VALA_CCODE_MODIFIERS_CONST);
		_tmp85_ = get_fun;
		vala_ccode_function_set_is_declaration (_tmp85_, TRUE);
		_tmp86_ = self->priv->declaration_fragment;
		_tmp87_ = get_fun;
		_tmp88_ = vala_ccode_function_copy (_tmp87_);
		_tmp89_ = _tmp88_;
		vala_ccode_fragment_append (_tmp86_, (ValaCCodeNode*) _tmp89_);
		_vala_ccode_node_unref0 (_tmp89_);
		_tmp90_ = get_fun;
		vala_ccode_function_set_is_declaration (_tmp90_, FALSE);
		_tmp91_ = get_fun;
		_tmp92_ = vala_ccode_block_new ();
		_tmp93_ = _tmp92_;
		vala_ccode_function_set_block (_tmp91_, _tmp93_);
		_vala_ccode_node_unref0 (_tmp93_);
		_tmp94_ = get_fun;
		_tmp95_ = vala_ccode_function_get_block (_tmp94_);
		_tmp96_ = _tmp95_;
		_tmp97_ = type_id_name;
		_tmp98_ = vala_ccode_identifier_new (_tmp97_);
		_tmp99_ = _tmp98_;
		_tmp100_ = vala_ccode_return_statement_new ((ValaCCodeExpression*) _tmp99_);
		_tmp101_ = _tmp100_;
		vala_ccode_block_add_statement (_tmp96_, (ValaCCodeNode*) _tmp101_);
		_vala_ccode_node_unref0 (_tmp101_);
		_vala_ccode_node_unref0 (_tmp99_);
		_tmp102_ = self->priv->definition_fragment;
		_tmp103_ = get_fun;
		vala_ccode_fragment_append (_tmp102_, (ValaCCodeNode*) _tmp103_);
		_vala_ccode_node_unref0 (get_fun);
	}
	type_value_table_decl_name = NULL;
	_tmp104_ = vala_ccode_block_new ();
	type_init = _tmp104_;
	_tmp105_ = fundamental;
	if (_tmp105_) {
		ValaCCodeDeclaration* cgtypetabledecl = NULL;
		ValaCCodeDeclaration* _tmp106_;
		ValaCCodeDeclaration* _tmp107_;
		ValaCCodeDeclaration* _tmp108_;
		gchar* _tmp109_;
		gchar* _tmp110_;
		gchar* _tmp111_;
		gchar* _tmp112_;
		gchar* _tmp113_;
		gchar* _tmp114_;
		gchar* _tmp115_;
		gchar* _tmp116_;
		gchar* _tmp117_;
		gchar* _tmp118_;
		gchar* _tmp119_;
		gchar* _tmp120_;
		gchar* _tmp121_;
		gchar* _tmp122_;
		ValaCCodeConstant* _tmp123_;
		ValaCCodeConstant* _tmp124_;
		ValaCCodeVariableDeclarator* _tmp125_;
		ValaCCodeVariableDeclarator* _tmp126_;
		gchar* _tmp127_;
		ValaCCodeBlock* _tmp128_;
		ValaCCodeDeclaration* _tmp129_;
		_tmp106_ = vala_ccode_declaration_new ("const GTypeValueTable");
		cgtypetabledecl = _tmp106_;
		_tmp107_ = cgtypetabledecl;
		vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp107_, VALA_CCODE_MODIFIERS_STATIC);
		_tmp108_ = cgtypetabledecl;
		_tmp109_ = vala_typeregister_function_get_gtype_value_table_init_function_name (self);
		_tmp110_ = _tmp109_;
		_tmp111_ = vala_typeregister_function_get_gtype_value_table_free_function_name (self);
		_tmp112_ = _tmp111_;
		_tmp113_ = vala_typeregister_function_get_gtype_value_table_copy_function_name (self);
		_tmp114_ = _tmp113_;
		_tmp115_ = vala_typeregister_function_get_gtype_value_table_peek_pointer_function_name (self);
		_tmp116_ = _tmp115_;
		_tmp117_ = vala_typeregister_function_get_gtype_value_table_collect_value_function_name (self);
		_tmp118_ = _tmp117_;
		_tmp119_ = vala_typeregister_function_get_gtype_value_table_lcopy_value_function_name (self);
		_tmp120_ = _tmp119_;
		_tmp121_ = g_strdup_printf ("{ %s, %s, %s, %s, \"p\", %s, \"p\", %s }", _tmp110_, _tmp112_, _tmp114_, _tmp116_, _tmp118_, _tmp120_);
		_tmp122_ = _tmp121_;
		_tmp123_ = vala_ccode_constant_new (_tmp122_);
		_tmp124_ = _tmp123_;
		_tmp125_ = vala_ccode_variable_declarator_new ("g_define_type_value_table", (ValaCCodeExpression*) _tmp124_, NULL);
		_tmp126_ = _tmp125_;
		vala_ccode_declaration_add_declarator (_tmp108_, (ValaCCodeDeclarator*) _tmp126_);
		_vala_ccode_node_unref0 (_tmp126_);
		_vala_ccode_node_unref0 (_tmp124_);
		_g_free0 (_tmp122_);
		_g_free0 (_tmp120_);
		_g_free0 (_tmp118_);
		_g_free0 (_tmp116_);
		_g_free0 (_tmp114_);
		_g_free0 (_tmp112_);
		_g_free0 (_tmp110_);
		_tmp127_ = g_strdup ("&g_define_type_value_table");
		_g_free0 (type_value_table_decl_name);
		type_value_table_decl_name = _tmp127_;
		_tmp128_ = type_init;
		_tmp129_ = cgtypetabledecl;
		vala_ccode_block_add_statement (_tmp128_, (ValaCCodeNode*) _tmp129_);
		_vala_ccode_node_unref0 (cgtypetabledecl);
	} else {
		gchar* _tmp130_;
		_tmp130_ = g_strdup ("NULL");
		_g_free0 (type_value_table_decl_name);
		type_value_table_decl_name = _tmp130_;
	}
	_tmp131_ = type_symbol;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp131_, VALA_TYPE_OBJECT_TYPE_SYMBOL)) {
		ValaCCodeDeclaration* ctypedecl = NULL;
		ValaCCodeDeclaration* _tmp132_;
		ValaCCodeDeclaration* _tmp133_;
		gchar* _tmp134_ = NULL;
		ValaCCodeDeclaration* _tmp137_;
		gchar* _tmp138_;
		gchar* _tmp139_;
		gchar* _tmp140_;
		gchar* _tmp141_;
		gchar* _tmp142_;
		gchar* _tmp143_;
		gchar* _tmp144_;
		gchar* _tmp145_;
		gchar* _tmp146_;
		gchar* _tmp147_;
		gchar* _tmp148_;
		gchar* _tmp149_;
		const gchar* _tmp150_;
		gchar* _tmp151_;
		gchar* _tmp152_;
		ValaCCodeConstant* _tmp153_;
		ValaCCodeConstant* _tmp154_;
		ValaCCodeVariableDeclarator* _tmp155_;
		ValaCCodeVariableDeclarator* _tmp156_;
		ValaCCodeBlock* _tmp157_;
		ValaCCodeDeclaration* _tmp158_;
		gboolean _tmp159_;
		_tmp132_ = vala_ccode_declaration_new ("const GTypeInfo");
		ctypedecl = _tmp132_;
		_tmp133_ = ctypedecl;
		vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp133_, VALA_CCODE_MODIFIERS_STATIC);
		if (plugin) {
			gchar* _tmp135_;
			_tmp135_ = vala_typeregister_function_get_base_finalize_func_name (self);
			_g_free0 (_tmp134_);
			_tmp134_ = _tmp135_;
		} else {
			gchar* _tmp136_;
			_tmp136_ = g_strdup ("NULL");
			_g_free0 (_tmp134_);
			_tmp134_ = _tmp136_;
		}
		_tmp137_ = ctypedecl;
		_tmp138_ = vala_typeregister_function_get_type_struct_name (self);
		_tmp139_ = _tmp138_;
		_tmp140_ = vala_typeregister_function_get_base_init_func_name (self);
		_tmp141_ = _tmp140_;
		_tmp142_ = vala_typeregister_function_get_class_init_func_name (self);
		_tmp143_ = _tmp142_;
		_tmp144_ = vala_typeregister_function_get_class_finalize_func_name (self);
		_tmp145_ = _tmp144_;
		_tmp146_ = vala_typeregister_function_get_instance_struct_size (self);
		_tmp147_ = _tmp146_;
		_tmp148_ = vala_typeregister_function_get_instance_init_func_name (self);
		_tmp149_ = _tmp148_;
		_tmp150_ = type_value_table_decl_name;
		_tmp151_ = g_strdup_printf ("{ sizeof (%s), (GBaseInitFunc) %s, (GBaseFinalizeFunc) %s, (GClassInit" \
"Func) %s, (GClassFinalizeFunc) %s, NULL, %s, 0, (GInstanceInitFunc) %s" \
", %s }", _tmp139_, _tmp141_, _tmp134_, _tmp143_, _tmp145_, _tmp147_, _tmp149_, _tmp150_);
		_tmp152_ = _tmp151_;
		_tmp153_ = vala_ccode_constant_new (_tmp152_);
		_tmp154_ = _tmp153_;
		_tmp155_ = vala_ccode_variable_declarator_new ("g_define_type_info", (ValaCCodeExpression*) _tmp154_, NULL);
		_tmp156_ = _tmp155_;
		vala_ccode_declaration_add_declarator (_tmp137_, (ValaCCodeDeclarator*) _tmp156_);
		_vala_ccode_node_unref0 (_tmp156_);
		_vala_ccode_node_unref0 (_tmp154_);
		_g_free0 (_tmp152_);
		_g_free0 (_tmp149_);
		_g_free0 (_tmp147_);
		_g_free0 (_tmp145_);
		_g_free0 (_tmp143_);
		_g_free0 (_tmp141_);
		_g_free0 (_tmp139_);
		_tmp157_ = type_init;
		_tmp158_ = ctypedecl;
		vala_ccode_block_add_statement (_tmp157_, (ValaCCodeNode*) _tmp158_);
		_tmp159_ = fundamental;
		if (_tmp159_) {
			ValaCCodeDeclaration* ctypefundamentaldecl = NULL;
			ValaCCodeDeclaration* _tmp160_;
			ValaCCodeDeclaration* _tmp161_;
			ValaCCodeDeclaration* _tmp162_;
			ValaCCodeConstant* _tmp163_;
			ValaCCodeConstant* _tmp164_;
			ValaCCodeVariableDeclarator* _tmp165_;
			ValaCCodeVariableDeclarator* _tmp166_;
			ValaCCodeBlock* _tmp167_;
			ValaCCodeDeclaration* _tmp168_;
			_tmp160_ = vala_ccode_declaration_new ("const GTypeFundamentalInfo");
			ctypefundamentaldecl = _tmp160_;
			_tmp161_ = ctypefundamentaldecl;
			vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp161_, VALA_CCODE_MODIFIERS_STATIC);
			_tmp162_ = ctypefundamentaldecl;
			_tmp163_ = vala_ccode_constant_new ("{ (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERI" \
"VABLE | G_TYPE_FLAG_DEEP_DERIVABLE) }");
			_tmp164_ = _tmp163_;
			_tmp165_ = vala_ccode_variable_declarator_new ("g_define_type_fundamental_info", (ValaCCodeExpression*) _tmp164_, NULL);
			_tmp166_ = _tmp165_;
			vala_ccode_declaration_add_declarator (_tmp162_, (ValaCCodeDeclarator*) _tmp166_);
			_vala_ccode_node_unref0 (_tmp166_);
			_vala_ccode_node_unref0 (_tmp164_);
			_tmp167_ = type_init;
			_tmp168_ = ctypefundamentaldecl;
			vala_ccode_block_add_statement (_tmp167_, (ValaCCodeNode*) _tmp168_);
			_vala_ccode_node_unref0 (ctypefundamentaldecl);
		}
		_g_free0 (_tmp134_);
		_vala_ccode_node_unref0 (ctypedecl);
	}
	_tmp169_ = type_init;
	_tmp170_ = vala_typeregister_function_get_type_interface_init_declaration (self);
	_tmp171_ = _tmp170_;
	vala_ccode_block_add_statement (_tmp169_, (ValaCCodeNode*) _tmp171_);
	_vala_ccode_node_unref0 (_tmp171_);
	_tmp172_ = type_symbol;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp172_, VALA_TYPE_STRUCT)) {
		ValaCCodeIdentifier* _tmp173_;
		ValaCCodeIdentifier* _tmp174_;
		ValaCCodeFunctionCall* _tmp175_;
		_tmp173_ = vala_ccode_identifier_new ("g_boxed_type_register_static");
		_tmp174_ = _tmp173_;
		_tmp175_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp174_);
		_vala_ccode_node_unref0 (reg_call);
		reg_call = _tmp175_;
		_vala_ccode_node_unref0 (_tmp174_);
	} else {
		ValaTypeSymbol* _tmp176_;
		_tmp176_ = type_symbol;
		if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp176_, VALA_TYPE_ENUM)) {
			ValaEnum* en = NULL;
			ValaTypeSymbol* _tmp177_;
			ValaEnum* _tmp178_;
			gboolean _tmp179_;
			gboolean _tmp180_;
			_tmp177_ = type_symbol;
			en = G_TYPE_CHECK_INSTANCE_CAST (_tmp177_, VALA_TYPE_ENUM, ValaEnum);
			_tmp178_ = en;
			_tmp179_ = vala_enum_get_is_flags (_tmp178_);
			_tmp180_ = _tmp179_;
			if (_tmp180_) {
				ValaCCodeIdentifier* _tmp181_;
				ValaCCodeIdentifier* _tmp182_;
				ValaCCodeFunctionCall* _tmp183_;
				_tmp181_ = vala_ccode_identifier_new ("g_flags_register_static");
				_tmp182_ = _tmp181_;
				_tmp183_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp182_);
				_vala_ccode_node_unref0 (reg_call);
				reg_call = _tmp183_;
				_vala_ccode_node_unref0 (_tmp182_);
			} else {
				ValaCCodeIdentifier* _tmp184_;
				ValaCCodeIdentifier* _tmp185_;
				ValaCCodeFunctionCall* _tmp186_;
				_tmp184_ = vala_ccode_identifier_new ("g_enum_register_static");
				_tmp185_ = _tmp184_;
				_tmp186_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp185_);
				_vala_ccode_node_unref0 (reg_call);
				reg_call = _tmp186_;
				_vala_ccode_node_unref0 (_tmp185_);
			}
		} else {
			gboolean _tmp187_;
			_tmp187_ = fundamental;
			if (_tmp187_) {
				ValaCCodeIdentifier* _tmp188_;
				ValaCCodeIdentifier* _tmp189_;
				ValaCCodeFunctionCall* _tmp190_;
				ValaCCodeFunctionCall* _tmp191_;
				ValaCCodeIdentifier* _tmp192_;
				ValaCCodeIdentifier* _tmp193_;
				ValaCCodeFunctionCall* _tmp194_;
				ValaCCodeFunctionCall* _tmp195_;
				_tmp188_ = vala_ccode_identifier_new ("g_type_register_fundamental");
				_tmp189_ = _tmp188_;
				_tmp190_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp189_);
				_vala_ccode_node_unref0 (reg_call);
				reg_call = _tmp190_;
				_vala_ccode_node_unref0 (_tmp189_);
				_tmp191_ = reg_call;
				_tmp192_ = vala_ccode_identifier_new ("g_type_fundamental_next");
				_tmp193_ = _tmp192_;
				_tmp194_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp193_);
				_tmp195_ = _tmp194_;
				vala_ccode_function_call_add_argument (_tmp191_, (ValaCCodeExpression*) _tmp195_);
				_vala_ccode_node_unref0 (_tmp195_);
				_vala_ccode_node_unref0 (_tmp193_);
			} else {
				if (!plugin) {
					ValaCCodeIdentifier* _tmp196_;
					ValaCCodeIdentifier* _tmp197_;
					ValaCCodeFunctionCall* _tmp198_;
					ValaCCodeFunctionCall* _tmp199_;
					gchar* _tmp200_;
					gchar* _tmp201_;
					ValaCCodeIdentifier* _tmp202_;
					ValaCCodeIdentifier* _tmp203_;
					_tmp196_ = vala_ccode_identifier_new ("g_type_register_static");
					_tmp197_ = _tmp196_;
					_tmp198_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp197_);
					_vala_ccode_node_unref0 (reg_call);
					reg_call = _tmp198_;
					_vala_ccode_node_unref0 (_tmp197_);
					_tmp199_ = reg_call;
					_tmp200_ = vala_typeregister_function_get_parent_type_name (self);
					_tmp201_ = _tmp200_;
					_tmp202_ = vala_ccode_identifier_new (_tmp201_);
					_tmp203_ = _tmp202_;
					vala_ccode_function_call_add_argument (_tmp199_, (ValaCCodeExpression*) _tmp203_);
					_vala_ccode_node_unref0 (_tmp203_);
					_g_free0 (_tmp201_);
				} else {
					ValaCCodeIdentifier* _tmp204_;
					ValaCCodeIdentifier* _tmp205_;
					ValaCCodeFunctionCall* _tmp206_;
					ValaCCodeFunctionCall* _tmp207_;
					ValaCCodeIdentifier* _tmp208_;
					ValaCCodeIdentifier* _tmp209_;
					ValaCCodeFunctionCall* _tmp210_;
					gchar* _tmp211_;
					gchar* _tmp212_;
					ValaCCodeIdentifier* _tmp213_;
					ValaCCodeIdentifier* _tmp214_;
					_tmp204_ = vala_ccode_identifier_new ("g_type_module_register_type");
					_tmp205_ = _tmp204_;
					_tmp206_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp205_);
					_vala_ccode_node_unref0 (reg_call);
					reg_call = _tmp206_;
					_vala_ccode_node_unref0 (_tmp205_);
					_tmp207_ = reg_call;
					_tmp208_ = vala_ccode_identifier_new ("module");
					_tmp209_ = _tmp208_;
					vala_ccode_function_call_add_argument (_tmp207_, (ValaCCodeExpression*) _tmp209_);
					_vala_ccode_node_unref0 (_tmp209_);
					_tmp210_ = reg_call;
					_tmp211_ = vala_typeregister_function_get_parent_type_name (self);
					_tmp212_ = _tmp211_;
					_tmp213_ = vala_ccode_identifier_new (_tmp212_);
					_tmp214_ = _tmp213_;
					vala_ccode_function_call_add_argument (_tmp210_, (ValaCCodeExpression*) _tmp214_);
					_vala_ccode_node_unref0 (_tmp214_);
					_g_free0 (_tmp212_);
				}
			}
		}
	}
	_tmp215_ = reg_call;
	_tmp216_ = type_symbol;
	_tmp217_ = vala_get_ccode_name ((ValaCodeNode*) _tmp216_);
	_tmp218_ = _tmp217_;
	_tmp219_ = g_strdup_printf ("\"%s\"", _tmp218_);
	_tmp220_ = _tmp219_;
	_tmp221_ = vala_ccode_constant_new (_tmp220_);
	_tmp222_ = _tmp221_;
	vala_ccode_function_call_add_argument (_tmp215_, (ValaCCodeExpression*) _tmp222_);
	_vala_ccode_node_unref0 (_tmp222_);
	_g_free0 (_tmp220_);
	_g_free0 (_tmp218_);
	_tmp223_ = type_symbol;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp223_, VALA_TYPE_STRUCT)) {
		ValaStruct* st = NULL;
		ValaTypeSymbol* _tmp224_;
		ValaStruct* _tmp225_;
		ValaCCodeFunctionCall* _tmp226_;
		ValaStruct* _tmp227_;
		gchar* _tmp228_;
		gchar* _tmp229_;
		ValaCCodeIdentifier* _tmp230_;
		ValaCCodeIdentifier* _tmp231_;
		ValaCCodeCastExpression* _tmp232_;
		ValaCCodeCastExpression* _tmp233_;
		ValaCCodeFunctionCall* _tmp234_;
		ValaStruct* _tmp235_;
		gchar* _tmp236_;
		gchar* _tmp237_;
		ValaCCodeIdentifier* _tmp238_;
		ValaCCodeIdentifier* _tmp239_;
		ValaCCodeCastExpression* _tmp240_;
		ValaCCodeCastExpression* _tmp241_;
		_tmp224_ = type_symbol;
		_tmp225_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp224_, VALA_TYPE_STRUCT, ValaStruct));
		st = _tmp225_;
		_tmp226_ = reg_call;
		_tmp227_ = st;
		_tmp228_ = vala_get_ccode_dup_function ((ValaTypeSymbol*) _tmp227_);
		_tmp229_ = _tmp228_;
		_tmp230_ = vala_ccode_identifier_new (_tmp229_);
		_tmp231_ = _tmp230_;
		_tmp232_ = vala_ccode_cast_expression_new ((ValaCCodeExpression*) _tmp231_, "GBoxedCopyFunc");
		_tmp233_ = _tmp232_;
		vala_ccode_function_call_add_argument (_tmp226_, (ValaCCodeExpression*) _tmp233_);
		_vala_ccode_node_unref0 (_tmp233_);
		_vala_ccode_node_unref0 (_tmp231_);
		_g_free0 (_tmp229_);
		_tmp234_ = reg_call;
		_tmp235_ = st;
		_tmp236_ = vala_get_ccode_free_function ((ValaTypeSymbol*) _tmp235_);
		_tmp237_ = _tmp236_;
		_tmp238_ = vala_ccode_identifier_new (_tmp237_);
		_tmp239_ = _tmp238_;
		_tmp240_ = vala_ccode_cast_expression_new ((ValaCCodeExpression*) _tmp239_, "GBoxedFreeFunc");
		_tmp241_ = _tmp240_;
		vala_ccode_function_call_add_argument (_tmp234_, (ValaCCodeExpression*) _tmp241_);
		_vala_ccode_node_unref0 (_tmp241_);
		_vala_ccode_node_unref0 (_tmp239_);
		_g_free0 (_tmp237_);
		_vala_code_node_unref0 (st);
	} else {
		ValaTypeSymbol* _tmp242_;
		_tmp242_ = type_symbol;
		if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp242_, VALA_TYPE_ENUM)) {
			ValaEnum* en = NULL;
			ValaTypeSymbol* _tmp243_;
			ValaCCodeInitializerList* clist = NULL;
			ValaCCodeInitializerList* _tmp244_;
			ValaCCodeInitializerList* clist_ev = NULL;
			ValaCCodeInitializerList* _tmp281_;
			ValaCCodeInitializerList* _tmp282_;
			ValaCCodeConstant* _tmp283_;
			ValaCCodeConstant* _tmp284_;
			ValaCCodeInitializerList* _tmp285_;
			ValaCCodeConstant* _tmp286_;
			ValaCCodeConstant* _tmp287_;
			ValaCCodeInitializerList* _tmp288_;
			ValaCCodeConstant* _tmp289_;
			ValaCCodeConstant* _tmp290_;
			ValaCCodeInitializerList* _tmp291_;
			ValaCCodeInitializerList* _tmp292_;
			ValaCCodeVariableDeclarator* enum_decl = NULL;
			ValaCCodeInitializerList* _tmp293_;
			ValaCCodeVariableDeclarator* _tmp294_;
			ValaEnum* _tmp295_;
			gboolean _tmp296_;
			gboolean _tmp297_;
			ValaCCodeDeclaration* _tmp300_;
			ValaCCodeVariableDeclarator* _tmp301_;
			ValaCCodeDeclaration* _tmp302_;
			ValaCCodeBlock* _tmp303_;
			ValaCCodeDeclaration* _tmp304_;
			ValaCCodeFunctionCall* _tmp305_;
			ValaCCodeIdentifier* _tmp306_;
			ValaCCodeIdentifier* _tmp307_;
			_tmp243_ = type_symbol;
			en = G_TYPE_CHECK_INSTANCE_CAST (_tmp243_, VALA_TYPE_ENUM, ValaEnum);
			_tmp244_ = vala_ccode_initializer_list_new ();
			clist = _tmp244_;
			clist_ev = NULL;
			{
				ValaList* _ev_list = NULL;
				ValaEnum* _tmp245_;
				ValaList* _tmp246_;
				gint _ev_size = 0;
				ValaList* _tmp247_;
				gint _tmp248_;
				gint _tmp249_;
				gint _ev_index = 0;
				_tmp245_ = en;
				_tmp246_ = vala_enum_get_values (_tmp245_);
				_ev_list = _tmp246_;
				_tmp247_ = _ev_list;
				_tmp248_ = vala_collection_get_size ((ValaCollection*) _tmp247_);
				_tmp249_ = _tmp248_;
				_ev_size = _tmp249_;
				_ev_index = -1;
				while (TRUE) {
					gint _tmp250_;
					gint _tmp251_;
					gint _tmp252_;
					ValaEnumValue* ev = NULL;
					ValaList* _tmp253_;
					gint _tmp254_;
					gpointer _tmp255_;
					ValaCCodeInitializerList* _tmp256_;
					ValaCCodeInitializerList* _tmp257_;
					ValaEnumValue* _tmp258_;
					gchar* _tmp259_;
					gchar* _tmp260_;
					ValaCCodeConstant* _tmp261_;
					ValaCCodeConstant* _tmp262_;
					ValaCCodeInitializerList* _tmp263_;
					ValaEnumValue* _tmp264_;
					gchar* _tmp265_;
					gchar* _tmp266_;
					gchar* _tmp267_;
					gchar* _tmp268_;
					ValaCCodeConstant* _tmp269_;
					ValaCCodeConstant* _tmp270_;
					ValaCCodeInitializerList* _tmp271_;
					ValaEnumValue* _tmp272_;
					const gchar* _tmp273_;
					const gchar* _tmp274_;
					gchar* _tmp275_;
					gchar* _tmp276_;
					ValaCCodeConstant* _tmp277_;
					ValaCCodeConstant* _tmp278_;
					ValaCCodeInitializerList* _tmp279_;
					ValaCCodeInitializerList* _tmp280_;
					_tmp250_ = _ev_index;
					_ev_index = _tmp250_ + 1;
					_tmp251_ = _ev_index;
					_tmp252_ = _ev_size;
					if (!(_tmp251_ < _tmp252_)) {
						break;
					}
					_tmp253_ = _ev_list;
					_tmp254_ = _ev_index;
					_tmp255_ = vala_list_get (_tmp253_, _tmp254_);
					ev = (ValaEnumValue*) _tmp255_;
					_tmp256_ = vala_ccode_initializer_list_new ();
					_vala_ccode_node_unref0 (clist_ev);
					clist_ev = _tmp256_;
					_tmp257_ = clist_ev;
					_tmp258_ = ev;
					_tmp259_ = vala_get_ccode_name ((ValaCodeNode*) _tmp258_);
					_tmp260_ = _tmp259_;
					_tmp261_ = vala_ccode_constant_new (_tmp260_);
					_tmp262_ = _tmp261_;
					vala_ccode_initializer_list_append (_tmp257_, (ValaCCodeExpression*) _tmp262_);
					_vala_ccode_node_unref0 (_tmp262_);
					_g_free0 (_tmp260_);
					_tmp263_ = clist_ev;
					_tmp264_ = ev;
					_tmp265_ = vala_get_ccode_name ((ValaCodeNode*) _tmp264_);
					_tmp266_ = _tmp265_;
					_tmp267_ = g_strdup_printf ("\"%s\"", _tmp266_);
					_tmp268_ = _tmp267_;
					_tmp269_ = vala_ccode_constant_new (_tmp268_);
					_tmp270_ = _tmp269_;
					vala_ccode_initializer_list_append (_tmp263_, (ValaCCodeExpression*) _tmp270_);
					_vala_ccode_node_unref0 (_tmp270_);
					_g_free0 (_tmp268_);
					_g_free0 (_tmp266_);
					_tmp271_ = clist_ev;
					_tmp272_ = ev;
					_tmp273_ = vala_enum_value_get_nick (_tmp272_);
					_tmp274_ = _tmp273_;
					_tmp275_ = g_strdup_printf ("\"%s\"", _tmp274_);
					_tmp276_ = _tmp275_;
					_tmp277_ = vala_ccode_constant_new (_tmp276_);
					_tmp278_ = _tmp277_;
					vala_ccode_initializer_list_append (_tmp271_, (ValaCCodeExpression*) _tmp278_);
					_vala_ccode_node_unref0 (_tmp278_);
					_g_free0 (_tmp276_);
					_tmp279_ = clist;
					_tmp280_ = clist_ev;
					vala_ccode_initializer_list_append (_tmp279_, (ValaCCodeExpression*) _tmp280_);
					_vala_code_node_unref0 (ev);
				}
				_vala_iterable_unref0 (_ev_list);
			}
			_tmp281_ = vala_ccode_initializer_list_new ();
			_vala_ccode_node_unref0 (clist_ev);
			clist_ev = _tmp281_;
			_tmp282_ = clist_ev;
			_tmp283_ = vala_ccode_constant_new ("0");
			_tmp284_ = _tmp283_;
			vala_ccode_initializer_list_append (_tmp282_, (ValaCCodeExpression*) _tmp284_);
			_vala_ccode_node_unref0 (_tmp284_);
			_tmp285_ = clist_ev;
			_tmp286_ = vala_ccode_constant_new ("NULL");
			_tmp287_ = _tmp286_;
			vala_ccode_initializer_list_append (_tmp285_, (ValaCCodeExpression*) _tmp287_);
			_vala_ccode_node_unref0 (_tmp287_);
			_tmp288_ = clist_ev;
			_tmp289_ = vala_ccode_constant_new ("NULL");
			_tmp290_ = _tmp289_;
			vala_ccode_initializer_list_append (_tmp288_, (ValaCCodeExpression*) _tmp290_);
			_vala_ccode_node_unref0 (_tmp290_);
			_tmp291_ = clist;
			_tmp292_ = clist_ev;
			vala_ccode_initializer_list_append (_tmp291_, (ValaCCodeExpression*) _tmp292_);
			_tmp293_ = clist;
			_tmp294_ = vala_ccode_variable_declarator_new ("values[]", (ValaCCodeExpression*) _tmp293_, NULL);
			enum_decl = _tmp294_;
			_tmp295_ = en;
			_tmp296_ = vala_enum_get_is_flags (_tmp295_);
			_tmp297_ = _tmp296_;
			if (_tmp297_) {
				ValaCCodeDeclaration* _tmp298_;
				_tmp298_ = vala_ccode_declaration_new ("const GFlagsValue");
				_vala_ccode_node_unref0 (_cdecl_);
				_cdecl_ = _tmp298_;
			} else {
				ValaCCodeDeclaration* _tmp299_;
				_tmp299_ = vala_ccode_declaration_new ("const GEnumValue");
				_vala_ccode_node_unref0 (_cdecl_);
				_cdecl_ = _tmp299_;
			}
			_tmp300_ = _cdecl_;
			_tmp301_ = enum_decl;
			vala_ccode_declaration_add_declarator (_tmp300_, (ValaCCodeDeclarator*) _tmp301_);
			_tmp302_ = _cdecl_;
			vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp302_, VALA_CCODE_MODIFIERS_STATIC);
			_tmp303_ = type_init;
			_tmp304_ = _cdecl_;
			vala_ccode_block_add_statement (_tmp303_, (ValaCCodeNode*) _tmp304_);
			_tmp305_ = reg_call;
			_tmp306_ = vala_ccode_identifier_new ("values");
			_tmp307_ = _tmp306_;
			vala_ccode_function_call_add_argument (_tmp305_, (ValaCCodeExpression*) _tmp307_);
			_vala_ccode_node_unref0 (_tmp307_);
			_vala_ccode_node_unref0 (enum_decl);
			_vala_ccode_node_unref0 (clist_ev);
			_vala_ccode_node_unref0 (clist);
		} else {
			ValaCCodeFunctionCall* _tmp308_;
			ValaCCodeIdentifier* _tmp309_;
			ValaCCodeIdentifier* _tmp310_;
			gboolean _tmp311_;
			ValaCCodeFunctionCall* _tmp315_;
			gchar* _tmp316_;
			gchar* _tmp317_;
			ValaCCodeConstant* _tmp318_;
			ValaCCodeConstant* _tmp319_;
			_tmp308_ = reg_call;
			_tmp309_ = vala_ccode_identifier_new ("&g_define_type_info");
			_tmp310_ = _tmp309_;
			vala_ccode_function_call_add_argument (_tmp308_, (ValaCCodeExpression*) _tmp310_);
			_vala_ccode_node_unref0 (_tmp310_);
			_tmp311_ = fundamental;
			if (_tmp311_) {
				ValaCCodeFunctionCall* _tmp312_;
				ValaCCodeIdentifier* _tmp313_;
				ValaCCodeIdentifier* _tmp314_;
				_tmp312_ = reg_call;
				_tmp313_ = vala_ccode_identifier_new ("&g_define_type_fundamental_info");
				_tmp314_ = _tmp313_;
				vala_ccode_function_call_add_argument (_tmp312_, (ValaCCodeExpression*) _tmp314_);
				_vala_ccode_node_unref0 (_tmp314_);
			}
			_tmp315_ = reg_call;
			_tmp316_ = vala_typeregister_function_get_type_flags (self);
			_tmp317_ = _tmp316_;
			_tmp318_ = vala_ccode_constant_new (_tmp317_);
			_tmp319_ = _tmp318_;
			vala_ccode_function_call_add_argument (_tmp315_, (ValaCCodeExpression*) _tmp319_);
			_vala_ccode_node_unref0 (_tmp319_);
			_g_free0 (_tmp317_);
		}
	}
	_tmp321_ = use_thread_safe;
	if (_tmp321_) {
		_tmp320_ = !plugin;
	} else {
		_tmp320_ = FALSE;
	}
	if (_tmp320_) {
		ValaCCodeDeclaration* temp_decl = NULL;
		ValaCCodeDeclaration* _tmp322_;
		ValaCCodeDeclaration* _tmp323_;
		const gchar* _tmp324_;
		ValaCCodeFunctionCall* _tmp325_;
		ValaCCodeVariableDeclarator* _tmp326_;
		ValaCCodeVariableDeclarator* _tmp327_;
		ValaCCodeBlock* _tmp328_;
		ValaCCodeDeclaration* _tmp329_;
		_tmp322_ = vala_ccode_declaration_new ("GType");
		temp_decl = _tmp322_;
		_tmp323_ = temp_decl;
		_tmp324_ = type_id_name;
		_tmp325_ = reg_call;
		_tmp326_ = vala_ccode_variable_declarator_new (_tmp324_, (ValaCCodeExpression*) _tmp325_, NULL);
		_tmp327_ = _tmp326_;
		vala_ccode_declaration_add_declarator (_tmp323_, (ValaCCodeDeclarator*) _tmp327_);
		_vala_ccode_node_unref0 (_tmp327_);
		_tmp328_ = type_init;
		_tmp329_ = temp_decl;
		vala_ccode_block_add_statement (_tmp328_, (ValaCCodeNode*) _tmp329_);
		_vala_ccode_node_unref0 (temp_decl);
	} else {
		ValaCCodeBlock* _tmp330_;
		const gchar* _tmp331_;
		ValaCCodeIdentifier* _tmp332_;
		ValaCCodeIdentifier* _tmp333_;
		ValaCCodeFunctionCall* _tmp334_;
		ValaCCodeAssignment* _tmp335_;
		ValaCCodeAssignment* _tmp336_;
		ValaCCodeExpressionStatement* _tmp337_;
		ValaCCodeExpressionStatement* _tmp338_;
		_tmp330_ = type_init;
		_tmp331_ = type_id_name;
		_tmp332_ = vala_ccode_identifier_new (_tmp331_);
		_tmp333_ = _tmp332_;
		_tmp334_ = reg_call;
		_tmp335_ = vala_ccode_assignment_new ((ValaCCodeExpression*) _tmp333_, (ValaCCodeExpression*) _tmp334_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
		_tmp336_ = _tmp335_;
		_tmp337_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) _tmp336_);
		_tmp338_ = _tmp337_;
		vala_ccode_block_add_statement (_tmp330_, (ValaCCodeNode*) _tmp338_);
		_vala_ccode_node_unref0 (_tmp338_);
		_vala_ccode_node_unref0 (_tmp336_);
		_vala_ccode_node_unref0 (_tmp333_);
	}
	_tmp340_ = cl;
	if (_tmp340_ != NULL) {
		ValaClass* _tmp341_;
		gboolean _tmp342_;
		gboolean _tmp343_;
		_tmp341_ = cl;
		_tmp342_ = vala_class_get_has_class_private_fields (_tmp341_);
		_tmp343_ = _tmp342_;
		_tmp339_ = _tmp343_;
	} else {
		_tmp339_ = FALSE;
	}
	if (_tmp339_) {
		ValaCCodeFunctionCall* add_class_private_call = NULL;
		ValaCCodeIdentifier* _tmp344_;
		ValaCCodeIdentifier* _tmp345_;
		ValaCCodeFunctionCall* _tmp346_;
		ValaCCodeFunctionCall* _tmp347_;
		const gchar* _tmp348_;
		ValaCCodeIdentifier* _tmp349_;
		ValaCCodeIdentifier* _tmp350_;
		ValaCCodeFunctionCall* _tmp351_;
		ValaTypeSymbol* _tmp352_;
		gchar* _tmp353_;
		gchar* _tmp354_;
		gchar* _tmp355_;
		gchar* _tmp356_;
		ValaCCodeIdentifier* _tmp357_;
		ValaCCodeIdentifier* _tmp358_;
		ValaCCodeBlock* _tmp359_;
		ValaCCodeFunctionCall* _tmp360_;
		ValaCCodeExpressionStatement* _tmp361_;
		ValaCCodeExpressionStatement* _tmp362_;
		_tmp344_ = vala_ccode_identifier_new ("g_type_add_class_private");
		_tmp345_ = _tmp344_;
		_tmp346_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp345_);
		_vala_ccode_node_unref0 (add_class_private_call);
		add_class_private_call = _tmp346_;
		_vala_ccode_node_unref0 (_tmp345_);
		_tmp347_ = add_class_private_call;
		_tmp348_ = type_id_name;
		_tmp349_ = vala_ccode_identifier_new (_tmp348_);
		_tmp350_ = _tmp349_;
		vala_ccode_function_call_add_argument (_tmp347_, (ValaCCodeExpression*) _tmp350_);
		_vala_ccode_node_unref0 (_tmp350_);
		_tmp351_ = add_class_private_call;
		_tmp352_ = type_symbol;
		_tmp353_ = vala_get_ccode_name ((ValaCodeNode*) _tmp352_);
		_tmp354_ = _tmp353_;
		_tmp355_ = g_strdup_printf ("sizeof (%sClassPrivate)", _tmp354_);
		_tmp356_ = _tmp355_;
		_tmp357_ = vala_ccode_identifier_new (_tmp356_);
		_tmp358_ = _tmp357_;
		vala_ccode_function_call_add_argument (_tmp351_, (ValaCCodeExpression*) _tmp358_);
		_vala_ccode_node_unref0 (_tmp358_);
		_g_free0 (_tmp356_);
		_g_free0 (_tmp354_);
		_tmp359_ = type_init;
		_tmp360_ = add_class_private_call;
		_tmp361_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) _tmp360_);
		_tmp362_ = _tmp361_;
		vala_ccode_block_add_statement (_tmp359_, (ValaCCodeNode*) _tmp362_);
		_vala_ccode_node_unref0 (_tmp362_);
		_vala_ccode_node_unref0 (add_class_private_call);
	}
	if (!declaration_only) {
		ValaCCodeBlock* _tmp363_;
		_tmp363_ = type_init;
		vala_typeregister_function_get_type_interface_init_statements (self, context, _tmp363_, plugin);
	}
	_tmp365_ = cl;
	if (_tmp365_ != NULL) {
		gboolean _tmp366_ = FALSE;
		ValaClass* _tmp367_;
		gboolean _tmp368_;
		gboolean _tmp369_;
		_tmp367_ = cl;
		_tmp368_ = vala_class_get_has_private_fields (_tmp367_);
		_tmp369_ = _tmp368_;
		if (_tmp369_) {
			_tmp366_ = TRUE;
		} else {
			ValaClass* _tmp370_;
			ValaList* _tmp371_;
			ValaList* _tmp372_;
			gint _tmp373_;
			gint _tmp374_;
			_tmp370_ = cl;
			_tmp371_ = vala_object_type_symbol_get_type_parameters ((ValaObjectTypeSymbol*) _tmp370_);
			_tmp372_ = _tmp371_;
			_tmp373_ = vala_collection_get_size ((ValaCollection*) _tmp372_);
			_tmp374_ = _tmp373_;
			_tmp366_ = _tmp374_ > 0;
			_vala_iterable_unref0 (_tmp372_);
		}
		_tmp364_ = _tmp366_;
	} else {
		_tmp364_ = FALSE;
	}
	if (_tmp364_) {
		if (!plugin) {
			ValaCCodeFunctionCall* ccall = NULL;
			ValaCCodeIdentifier* _tmp375_;
			ValaCCodeIdentifier* _tmp376_;
			ValaCCodeFunctionCall* _tmp377_;
			ValaCCodeFunctionCall* _tmp378_;
			ValaCCodeFunctionCall* _tmp379_;
			const gchar* _tmp380_;
			ValaCCodeIdentifier* _tmp381_;
			ValaCCodeIdentifier* _tmp382_;
			ValaCCodeFunctionCall* _tmp383_;
			ValaClass* _tmp384_;
			gchar* _tmp385_;
			gchar* _tmp386_;
			gchar* _tmp387_;
			gchar* _tmp388_;
			ValaCCodeIdentifier* _tmp389_;
			ValaCCodeIdentifier* _tmp390_;
			ValaCCodeBlock* _tmp391_;
			ValaClass* _tmp392_;
			gchar* _tmp393_;
			gchar* _tmp394_;
			gchar* _tmp395_;
			gchar* _tmp396_;
			ValaCCodeIdentifier* _tmp397_;
			ValaCCodeIdentifier* _tmp398_;
			ValaCCodeFunctionCall* _tmp399_;
			ValaCCodeAssignment* _tmp400_;
			ValaCCodeAssignment* _tmp401_;
			ValaCCodeExpressionStatement* _tmp402_;
			ValaCCodeExpressionStatement* _tmp403_;
			_tmp375_ = vala_ccode_identifier_new ("g_type_add_instance_private");
			_tmp376_ = _tmp375_;
			_tmp377_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp376_);
			_tmp378_ = _tmp377_;
			_vala_ccode_node_unref0 (_tmp376_);
			ccall = _tmp378_;
			_tmp379_ = ccall;
			_tmp380_ = type_id_name;
			_tmp381_ = vala_ccode_identifier_new (_tmp380_);
			_tmp382_ = _tmp381_;
			vala_ccode_function_call_add_argument (_tmp379_, (ValaCCodeExpression*) _tmp382_);
			_vala_ccode_node_unref0 (_tmp382_);
			_tmp383_ = ccall;
			_tmp384_ = cl;
			_tmp385_ = vala_get_ccode_name ((ValaCodeNode*) _tmp384_);
			_tmp386_ = _tmp385_;
			_tmp387_ = g_strdup_printf ("sizeof (%sPrivate)", _tmp386_);
			_tmp388_ = _tmp387_;
			_tmp389_ = vala_ccode_identifier_new (_tmp388_);
			_tmp390_ = _tmp389_;
			vala_ccode_function_call_add_argument (_tmp383_, (ValaCCodeExpression*) _tmp390_);
			_vala_ccode_node_unref0 (_tmp390_);
			_g_free0 (_tmp388_);
			_g_free0 (_tmp386_);
			_tmp391_ = type_init;
			_tmp392_ = cl;
			_tmp393_ = vala_get_ccode_name ((ValaCodeNode*) _tmp392_);
			_tmp394_ = _tmp393_;
			_tmp395_ = g_strdup_printf ("%s_private_offset", _tmp394_);
			_tmp396_ = _tmp395_;
			_tmp397_ = vala_ccode_identifier_new (_tmp396_);
			_tmp398_ = _tmp397_;
			_tmp399_ = ccall;
			_tmp400_ = vala_ccode_assignment_new ((ValaCCodeExpression*) _tmp398_, (ValaCCodeExpression*) _tmp399_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
			_tmp401_ = _tmp400_;
			_tmp402_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) _tmp401_);
			_tmp403_ = _tmp402_;
			vala_ccode_block_add_statement (_tmp391_, (ValaCCodeNode*) _tmp403_);
			_vala_ccode_node_unref0 (_tmp403_);
			_vala_ccode_node_unref0 (_tmp401_);
			_vala_ccode_node_unref0 (_tmp398_);
			_g_free0 (_tmp396_);
			_g_free0 (_tmp394_);
			_vala_ccode_node_unref0 (ccall);
		} else {
			ValaCCodeBlock* _tmp404_;
			ValaClass* _tmp405_;
			gchar* _tmp406_;
			gchar* _tmp407_;
			gchar* _tmp408_;
			gchar* _tmp409_;
			ValaCCodeIdentifier* _tmp410_;
			ValaCCodeIdentifier* _tmp411_;
			ValaClass* _tmp412_;
			gchar* _tmp413_;
			gchar* _tmp414_;
			gchar* _tmp415_;
			gchar* _tmp416_;
			ValaCCodeIdentifier* _tmp417_;
			ValaCCodeIdentifier* _tmp418_;
			ValaCCodeAssignment* _tmp419_;
			ValaCCodeAssignment* _tmp420_;
			ValaCCodeExpressionStatement* _tmp421_;
			ValaCCodeExpressionStatement* _tmp422_;
			_tmp404_ = type_init;
			_tmp405_ = cl;
			_tmp406_ = vala_get_ccode_name ((ValaCodeNode*) _tmp405_);
			_tmp407_ = _tmp406_;
			_tmp408_ = g_strdup_printf ("%s_private_offset", _tmp407_);
			_tmp409_ = _tmp408_;
			_tmp410_ = vala_ccode_identifier_new (_tmp409_);
			_tmp411_ = _tmp410_;
			_tmp412_ = cl;
			_tmp413_ = vala_get_ccode_name ((ValaCodeNode*) _tmp412_);
			_tmp414_ = _tmp413_;
			_tmp415_ = g_strdup_printf ("sizeof (%sPrivate)", _tmp414_);
			_tmp416_ = _tmp415_;
			_tmp417_ = vala_ccode_identifier_new (_tmp416_);
			_tmp418_ = _tmp417_;
			_tmp419_ = vala_ccode_assignment_new ((ValaCCodeExpression*) _tmp411_, (ValaCCodeExpression*) _tmp418_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
			_tmp420_ = _tmp419_;
			_tmp421_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) _tmp420_);
			_tmp422_ = _tmp421_;
			vala_ccode_block_add_statement (_tmp404_, (ValaCCodeNode*) _tmp422_);
			_vala_ccode_node_unref0 (_tmp422_);
			_vala_ccode_node_unref0 (_tmp420_);
			_vala_ccode_node_unref0 (_tmp418_);
			_g_free0 (_tmp416_);
			_g_free0 (_tmp414_);
			_vala_ccode_node_unref0 (_tmp411_);
			_g_free0 (_tmp409_);
			_g_free0 (_tmp407_);
		}
	}
	if (!plugin) {
		ValaCCodeExpression* condition = NULL;
		gboolean _tmp423_;
		ValaCCodeExpression* cond = NULL;
		gboolean _tmp464_;
		ValaCCodeIfStatement* cif = NULL;
		ValaCCodeExpression* _tmp472_;
		ValaCCodeBlock* _tmp473_;
		ValaCCodeIfStatement* _tmp474_;
		ValaCCodeBlock* _tmp475_;
		ValaCCodeIfStatement* _tmp476_;
		_tmp423_ = use_thread_safe;
		if (_tmp423_) {
			ValaCCodeFunctionCall* enter = NULL;
			ValaCCodeIdentifier* _tmp424_;
			ValaCCodeIdentifier* _tmp425_;
			ValaCCodeFunctionCall* _tmp426_;
			ValaCCodeFunctionCall* _tmp427_;
			ValaCCodeFunctionCall* _tmp428_;
			const gchar* _tmp429_;
			gchar* _tmp430_;
			gchar* _tmp431_;
			ValaCCodeIdentifier* _tmp432_;
			ValaCCodeIdentifier* _tmp433_;
			ValaCCodeUnaryExpression* _tmp434_;
			ValaCCodeUnaryExpression* _tmp435_;
			ValaCCodeFunctionCall* _tmp436_;
			ValaCCodeExpression* _tmp437_;
			ValaCCodeFunctionCall* leave = NULL;
			ValaCCodeIdentifier* _tmp438_;
			ValaCCodeIdentifier* _tmp439_;
			ValaCCodeFunctionCall* _tmp440_;
			ValaCCodeFunctionCall* _tmp441_;
			ValaCCodeFunctionCall* _tmp442_;
			const gchar* _tmp443_;
			gchar* _tmp444_;
			gchar* _tmp445_;
			ValaCCodeIdentifier* _tmp446_;
			ValaCCodeIdentifier* _tmp447_;
			ValaCCodeUnaryExpression* _tmp448_;
			ValaCCodeUnaryExpression* _tmp449_;
			ValaCCodeFunctionCall* _tmp450_;
			const gchar* _tmp451_;
			ValaCCodeIdentifier* _tmp452_;
			ValaCCodeIdentifier* _tmp453_;
			ValaCCodeBlock* _tmp454_;
			ValaCCodeFunctionCall* _tmp455_;
			ValaCCodeExpressionStatement* _tmp456_;
			ValaCCodeExpressionStatement* _tmp457_;
			_tmp424_ = vala_ccode_identifier_new ("g_once_init_enter");
			_tmp425_ = _tmp424_;
			_tmp426_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp425_);
			_tmp427_ = _tmp426_;
			_vala_ccode_node_unref0 (_tmp425_);
			enter = _tmp427_;
			_tmp428_ = enter;
			_tmp429_ = type_id_name;
			_tmp430_ = g_strconcat (_tmp429_, "__volatile", NULL);
			_tmp431_ = _tmp430_;
			_tmp432_ = vala_ccode_identifier_new (_tmp431_);
			_tmp433_ = _tmp432_;
			_tmp434_ = vala_ccode_unary_expression_new (VALA_CCODE_UNARY_OPERATOR_ADDRESS_OF, (ValaCCodeExpression*) _tmp433_);
			_tmp435_ = _tmp434_;
			vala_ccode_function_call_add_argument (_tmp428_, (ValaCCodeExpression*) _tmp435_);
			_vala_ccode_node_unref0 (_tmp435_);
			_vala_ccode_node_unref0 (_tmp433_);
			_g_free0 (_tmp431_);
			_tmp436_ = enter;
			_tmp437_ = _vala_ccode_node_ref0 ((ValaCCodeExpression*) _tmp436_);
			_vala_ccode_node_unref0 (condition);
			condition = _tmp437_;
			_tmp438_ = vala_ccode_identifier_new ("g_once_init_leave");
			_tmp439_ = _tmp438_;
			_tmp440_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp439_);
			_tmp441_ = _tmp440_;
			_vala_ccode_node_unref0 (_tmp439_);
			leave = _tmp441_;
			_tmp442_ = leave;
			_tmp443_ = type_id_name;
			_tmp444_ = g_strconcat (_tmp443_, "__volatile", NULL);
			_tmp445_ = _tmp444_;
			_tmp446_ = vala_ccode_identifier_new (_tmp445_);
			_tmp447_ = _tmp446_;
			_tmp448_ = vala_ccode_unary_expression_new (VALA_CCODE_UNARY_OPERATOR_ADDRESS_OF, (ValaCCodeExpression*) _tmp447_);
			_tmp449_ = _tmp448_;
			vala_ccode_function_call_add_argument (_tmp442_, (ValaCCodeExpression*) _tmp449_);
			_vala_ccode_node_unref0 (_tmp449_);
			_vala_ccode_node_unref0 (_tmp447_);
			_g_free0 (_tmp445_);
			_tmp450_ = leave;
			_tmp451_ = type_id_name;
			_tmp452_ = vala_ccode_identifier_new (_tmp451_);
			_tmp453_ = _tmp452_;
			vala_ccode_function_call_add_argument (_tmp450_, (ValaCCodeExpression*) _tmp453_);
			_vala_ccode_node_unref0 (_tmp453_);
			_tmp454_ = type_init;
			_tmp455_ = leave;
			_tmp456_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) _tmp455_);
			_tmp457_ = _tmp456_;
			vala_ccode_block_add_statement (_tmp454_, (ValaCCodeNode*) _tmp457_);
			_vala_ccode_node_unref0 (_tmp457_);
			_vala_ccode_node_unref0 (leave);
			_vala_ccode_node_unref0 (enter);
		} else {
			ValaCCodeIdentifier* id = NULL;
			const gchar* _tmp458_;
			ValaCCodeIdentifier* _tmp459_;
			ValaCCodeConstant* zero = NULL;
			ValaCCodeConstant* _tmp460_;
			ValaCCodeIdentifier* _tmp461_;
			ValaCCodeConstant* _tmp462_;
			ValaCCodeBinaryExpression* _tmp463_;
			_tmp458_ = type_id_name;
			_tmp459_ = vala_ccode_identifier_new (_tmp458_);
			id = _tmp459_;
			_tmp460_ = vala_ccode_constant_new ("0");
			zero = _tmp460_;
			_tmp461_ = id;
			_tmp462_ = zero;
			_tmp463_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_EQUALITY, (ValaCCodeExpression*) _tmp461_, (ValaCCodeExpression*) _tmp462_);
			_vala_ccode_node_unref0 (condition);
			condition = (ValaCCodeExpression*) _tmp463_;
			_vala_ccode_node_unref0 (zero);
			_vala_ccode_node_unref0 (id);
		}
		_tmp464_ = use_thread_safe;
		if (_tmp464_) {
			ValaCCodeExpression* _tmp465_;
			ValaCCodeExpression* _tmp466_;
			_tmp465_ = condition;
			_tmp466_ = _vala_ccode_node_ref0 (_tmp465_);
			_vala_ccode_node_unref0 (cond);
			cond = _tmp466_;
		} else {
			ValaCCodeIdentifier* _tmp467_;
			ValaCCodeIdentifier* _tmp468_;
			ValaCCodeFunctionCall* _tmp469_;
			ValaCCodeExpression* _tmp470_;
			ValaCCodeExpression* _tmp471_;
			_tmp467_ = vala_ccode_identifier_new ("G_UNLIKELY");
			_tmp468_ = _tmp467_;
			_tmp469_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp468_);
			_vala_ccode_node_unref0 (cond);
			cond = (ValaCCodeExpression*) _tmp469_;
			_vala_ccode_node_unref0 (_tmp468_);
			_tmp470_ = cond;
			_tmp471_ = condition;
			vala_ccode_function_call_add_argument (G_TYPE_CHECK_INSTANCE_CAST (_tmp470_, VALA_TYPE_CCODE_FUNCTION_CALL, ValaCCodeFunctionCall), _tmp471_);
		}
		_tmp472_ = cond;
		_tmp473_ = type_init;
		_tmp474_ = vala_ccode_if_statement_new (_tmp472_, (ValaCCodeStatement*) _tmp473_, NULL);
		cif = _tmp474_;
		_tmp475_ = type_block;
		_tmp476_ = cif;
		vala_ccode_block_add_statement (_tmp475_, (ValaCCodeNode*) _tmp476_);
		_vala_ccode_node_unref0 (cif);
		_vala_ccode_node_unref0 (cond);
		_vala_ccode_node_unref0 (condition);
	} else {
		ValaCCodeBlock* _tmp477_;
		ValaCCodeBlock* _tmp478_;
		_tmp477_ = type_init;
		_tmp478_ = _vala_ccode_node_ref0 (_tmp477_);
		_vala_ccode_node_unref0 (type_block);
		type_block = _tmp478_;
	}
	_tmp479_ = use_thread_safe;
	if (_tmp479_) {
		ValaCCodeBlock* _tmp480_;
		const gchar* _tmp481_;
		gchar* _tmp482_;
		gchar* _tmp483_;
		ValaCCodeIdentifier* _tmp484_;
		ValaCCodeIdentifier* _tmp485_;
		ValaCCodeReturnStatement* _tmp486_;
		ValaCCodeReturnStatement* _tmp487_;
		_tmp480_ = type_block;
		_tmp481_ = type_id_name;
		_tmp482_ = g_strconcat (_tmp481_, "__volatile", NULL);
		_tmp483_ = _tmp482_;
		_tmp484_ = vala_ccode_identifier_new (_tmp483_);
		_tmp485_ = _tmp484_;
		_tmp486_ = vala_ccode_return_statement_new ((ValaCCodeExpression*) _tmp485_);
		_tmp487_ = _tmp486_;
		vala_ccode_block_add_statement (_tmp480_, (ValaCCodeNode*) _tmp487_);
		_vala_ccode_node_unref0 (_tmp487_);
		_vala_ccode_node_unref0 (_tmp485_);
		_g_free0 (_tmp483_);
	} else {
		ValaCCodeBlock* _tmp488_;
		const gchar* _tmp489_;
		ValaCCodeIdentifier* _tmp490_;
		ValaCCodeIdentifier* _tmp491_;
		ValaCCodeReturnStatement* _tmp492_;
		ValaCCodeReturnStatement* _tmp493_;
		_tmp488_ = type_block;
		_tmp489_ = type_id_name;
		_tmp490_ = vala_ccode_identifier_new (_tmp489_);
		_tmp491_ = _tmp490_;
		_tmp492_ = vala_ccode_return_statement_new ((ValaCCodeExpression*) _tmp491_);
		_tmp493_ = _tmp492_;
		vala_ccode_block_add_statement (_tmp488_, (ValaCCodeNode*) _tmp493_);
		_vala_ccode_node_unref0 (_tmp493_);
		_vala_ccode_node_unref0 (_tmp491_);
	}
	_tmp494_ = fun;
	_tmp495_ = type_block;
	vala_ccode_function_set_block (_tmp494_, _tmp495_);
	_tmp496_ = self->priv->definition_fragment;
	_tmp497_ = fun;
	vala_ccode_fragment_append (_tmp496_, (ValaCCodeNode*) _tmp497_);
	_vala_ccode_node_unref0 (reg_call);
	_vala_ccode_node_unref0 (type_init);
	_g_free0 (type_value_table_decl_name);
	_vala_ccode_node_unref0 (fun);
	_vala_ccode_node_unref0 (_cdecl_);
	_vala_ccode_node_unref0 (type_block);
	_g_free0 (type_id_name);
	_vala_code_node_unref0 (type_symbol);
}


/**
 * Returns the data type to be registered.
 *
 * @return type to be registered
 */
static ValaTypeSymbol*
vala_typeregister_function_real_get_type_declaration (ValaTypeRegisterFunction* self)
{
	g_critical ("Type `%s' does not implement abstract method `vala_typeregister_function_get_type_declaration'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return NULL;
}


ValaTypeSymbol*
vala_typeregister_function_get_type_declaration (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_type_declaration (self);
}


/**
 * Returns the name of the type struct in C code.
 *
 * @return C struct name
 */
static gchar*
vala_typeregister_function_real_get_type_struct_name (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar*
vala_typeregister_function_get_type_struct_name (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_type_struct_name (self);
}


/**
 * Returns the name of the base_init function in C code.
 *
 * @return C function name
 */
static gchar*
vala_typeregister_function_real_get_base_init_func_name (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar*
vala_typeregister_function_get_base_init_func_name (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_base_init_func_name (self);
}


/**
 * Returns the name of the class_finalize function in C code.
 *
 * @return C function name
 */
static gchar*
vala_typeregister_function_real_get_class_finalize_func_name (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar*
vala_typeregister_function_get_class_finalize_func_name (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_class_finalize_func_name (self);
}


/**
 * Returns the name of the base_finalize function in C code.
 *
 * @return C function name
 */
static gchar*
vala_typeregister_function_real_get_base_finalize_func_name (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar*
vala_typeregister_function_get_base_finalize_func_name (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_base_finalize_func_name (self);
}


/**
 * Returns the name of the class_init function in C code.
 *
 * @return C function name
 */
static gchar*
vala_typeregister_function_real_get_class_init_func_name (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar*
vala_typeregister_function_get_class_init_func_name (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_class_init_func_name (self);
}


/**
 * Returns the size of the instance struct in C code.
 *
 * @return C instance struct size
 */
static gchar*
vala_typeregister_function_real_get_instance_struct_size (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar*
vala_typeregister_function_get_instance_struct_size (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_instance_struct_size (self);
}


/**
 * Returns the name of the instance_init function in C code.
 *
 * @return C function name
 */
static gchar*
vala_typeregister_function_real_get_instance_init_func_name (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar*
vala_typeregister_function_get_instance_init_func_name (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_instance_init_func_name (self);
}


/**
 * Returns the name of the parent type in C code.
 *
 * @return C function name
 */
static gchar*
vala_typeregister_function_real_get_parent_type_name (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar*
vala_typeregister_function_get_parent_type_name (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_parent_type_name (self);
}


/**
 * Returns the C-name of the new generated GTypeValueTable init function or null when not available.
 *
 * @return C function name
 */
static gchar*
vala_typeregister_function_real_get_gtype_value_table_init_function_name (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	result = NULL;
	return result;
}


gchar*
vala_typeregister_function_get_gtype_value_table_init_function_name (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_gtype_value_table_init_function_name (self);
}


/**
 * Returns the C-name of the new generated GTypeValueTable peek pointer function or null when not available.
 *
 * @return C function name
 */
static gchar*
vala_typeregister_function_real_get_gtype_value_table_peek_pointer_function_name (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	result = NULL;
	return result;
}


gchar*
vala_typeregister_function_get_gtype_value_table_peek_pointer_function_name (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_gtype_value_table_peek_pointer_function_name (self);
}


/**
 * Returns the C-name of the new generated GTypeValueTable free function or null when not available.
 *
 * @return C function name
 */
static gchar*
vala_typeregister_function_real_get_gtype_value_table_free_function_name (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	result = NULL;
	return result;
}


gchar*
vala_typeregister_function_get_gtype_value_table_free_function_name (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_gtype_value_table_free_function_name (self);
}


/**
 * Returns the C-name of the new generated GTypeValueTable copy function or null when not available.
 *
 * @return C function name
 */
static gchar*
vala_typeregister_function_real_get_gtype_value_table_copy_function_name (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	result = NULL;
	return result;
}


gchar*
vala_typeregister_function_get_gtype_value_table_copy_function_name (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_gtype_value_table_copy_function_name (self);
}


/**
 * Returns the C-name of the new generated GTypeValueTable lcopy function or null when not available.
 *
 * @return C function name
 */
static gchar*
vala_typeregister_function_real_get_gtype_value_table_lcopy_value_function_name (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	result = NULL;
	return result;
}


gchar*
vala_typeregister_function_get_gtype_value_table_lcopy_value_function_name (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_gtype_value_table_lcopy_value_function_name (self);
}


/**
 * Returns the C-name of the new generated GTypeValueTable collect value function or null when not available.
 *
 * @return C function name
 */
static gchar*
vala_typeregister_function_real_get_gtype_value_table_collect_value_function_name (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	result = NULL;
	return result;
}


gchar*
vala_typeregister_function_get_gtype_value_table_collect_value_function_name (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_gtype_value_table_collect_value_function_name (self);
}


/**
 * Returns the set of type flags to be applied when registering.
 *
 * @return type flags
 */
static gchar*
vala_typeregister_function_real_get_type_flags (ValaTypeRegisterFunction* self)
{
	gchar* result = NULL;
	gchar* _tmp0_;
	_tmp0_ = g_strdup ("0");
	result = _tmp0_;
	return result;
}


gchar*
vala_typeregister_function_get_type_flags (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_type_flags (self);
}


/**
 * Returns additional C declarations to setup interfaces.
 *
 * @return C declarations
 */
static ValaCCodeFragment*
vala_typeregister_function_real_get_type_interface_init_declaration (ValaTypeRegisterFunction* self)
{
	ValaCCodeFragment* result = NULL;
	ValaCCodeFragment* _tmp0_;
	_tmp0_ = vala_ccode_fragment_new ();
	result = _tmp0_;
	return result;
}


ValaCCodeFragment*
vala_typeregister_function_get_type_interface_init_declaration (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_type_interface_init_declaration (self);
}


/**
 * Returns additional C initialization statements to setup interfaces.
 */
static void
vala_typeregister_function_real_get_type_interface_init_statements (ValaTypeRegisterFunction* self,
                                                                    ValaCodeContext* context,
                                                                    ValaCCodeBlock* block,
                                                                    gboolean plugin)
{
	g_return_if_fail (context != NULL);
	g_return_if_fail (block != NULL);
}


void
vala_typeregister_function_get_type_interface_init_statements (ValaTypeRegisterFunction* self,
                                                               ValaCodeContext* context,
                                                               ValaCCodeBlock* block,
                                                               gboolean plugin)
{
	g_return_if_fail (self != NULL);
	VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_type_interface_init_statements (self, context, block, plugin);
}


ValaCCodeFragment*
vala_typeregister_function_get_source_declaration (ValaTypeRegisterFunction* self)
{
	ValaCCodeFragment* result = NULL;
	ValaCCodeFragment* _tmp0_;
	ValaCCodeFragment* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->source_declaration_fragment;
	_tmp1_ = _vala_ccode_node_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


/**
 * Returns the declaration for this type register function in C code.
 *
 * @return C function declaration fragment
 */
ValaCCodeFragment*
vala_typeregister_function_get_declaration (ValaTypeRegisterFunction* self)
{
	ValaCCodeFragment* result = NULL;
	ValaCCodeFragment* _tmp0_;
	ValaCCodeFragment* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->declaration_fragment;
	_tmp1_ = _vala_ccode_node_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


/**
 * Returns the definition for this type register function in C code.
 *
 * @return C function definition fragment
 */
ValaCCodeFragment*
vala_typeregister_function_get_definition (ValaTypeRegisterFunction* self)
{
	ValaCCodeFragment* result = NULL;
	ValaCCodeFragment* _tmp0_;
	ValaCCodeFragment* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->definition_fragment;
	_tmp1_ = _vala_ccode_node_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


/**
 * Returns the accessibility for this type.
 */
static ValaSymbolAccessibility
vala_typeregister_function_real_get_accessibility (ValaTypeRegisterFunction* self)
{
	g_critical ("Type `%s' does not implement abstract method `vala_typeregister_function_get_accessibility'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return 0;
}


ValaSymbolAccessibility
vala_typeregister_function_get_accessibility (ValaTypeRegisterFunction* self)
{
	g_return_val_if_fail (self != NULL, 0);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_accessibility (self);
}


ValaTypeRegisterFunction*
vala_typeregister_function_construct (GType object_type)
{
	ValaTypeRegisterFunction* self = NULL;
	self = (ValaTypeRegisterFunction*) g_type_create_instance (object_type);
	return self;
}


static void
vala_value_typeregister_function_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}


static void
vala_value_typeregister_function_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		vala_typeregister_function_unref (value->data[0].v_pointer);
	}
}


static void
vala_value_typeregister_function_copy_value (const GValue* src_value,
                                             GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = vala_typeregister_function_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer
vala_value_typeregister_function_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}


static gchar*
vala_value_typeregister_function_collect_value (GValue* value,
                                                guint n_collect_values,
                                                GTypeCValue* collect_values,
                                                guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		ValaTypeRegisterFunction * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = vala_typeregister_function_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar*
vala_value_typeregister_function_lcopy_value (const GValue* value,
                                              guint n_collect_values,
                                              GTypeCValue* collect_values,
                                              guint collect_flags)
{
	ValaTypeRegisterFunction ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = vala_typeregister_function_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec*
vala_param_spec_typeregister_function (const gchar* name,
                                       const gchar* nick,
                                       const gchar* blurb,
                                       GType object_type,
                                       GParamFlags flags)
{
	ValaParamSpecTypeRegisterFunction* spec;
	g_return_val_if_fail (g_type_is_a (object_type, VALA_TYPE_TYPEREGISTER_FUNCTION), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer
vala_value_get_typeregister_function (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALA_TYPE_TYPEREGISTER_FUNCTION), NULL);
	return value->data[0].v_pointer;
}


void
vala_value_set_typeregister_function (GValue* value,
                                      gpointer v_object)
{
	ValaTypeRegisterFunction * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALA_TYPE_TYPEREGISTER_FUNCTION));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, VALA_TYPE_TYPEREGISTER_FUNCTION));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		vala_typeregister_function_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		vala_typeregister_function_unref (old);
	}
}


void
vala_value_take_typeregister_function (GValue* value,
                                       gpointer v_object)
{
	ValaTypeRegisterFunction * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALA_TYPE_TYPEREGISTER_FUNCTION));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, VALA_TYPE_TYPEREGISTER_FUNCTION));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		vala_typeregister_function_unref (old);
	}
}


static void
vala_typeregister_function_class_init (ValaTypeRegisterFunctionClass * klass)
{
	vala_typeregister_function_parent_class = g_type_class_peek_parent (klass);
	((ValaTypeRegisterFunctionClass *) klass)->finalize = vala_typeregister_function_finalize;
	g_type_class_adjust_private_offset (klass, &ValaTypeRegisterFunction_private_offset);
	((ValaTypeRegisterFunctionClass *) klass)->get_type_declaration = (ValaTypeSymbol* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_type_declaration;
	((ValaTypeRegisterFunctionClass *) klass)->get_type_struct_name = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_type_struct_name;
	((ValaTypeRegisterFunctionClass *) klass)->get_base_init_func_name = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_base_init_func_name;
	((ValaTypeRegisterFunctionClass *) klass)->get_class_finalize_func_name = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_class_finalize_func_name;
	((ValaTypeRegisterFunctionClass *) klass)->get_base_finalize_func_name = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_base_finalize_func_name;
	((ValaTypeRegisterFunctionClass *) klass)->get_class_init_func_name = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_class_init_func_name;
	((ValaTypeRegisterFunctionClass *) klass)->get_instance_struct_size = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_instance_struct_size;
	((ValaTypeRegisterFunctionClass *) klass)->get_instance_init_func_name = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_instance_init_func_name;
	((ValaTypeRegisterFunctionClass *) klass)->get_parent_type_name = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_parent_type_name;
	((ValaTypeRegisterFunctionClass *) klass)->get_gtype_value_table_init_function_name = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_gtype_value_table_init_function_name;
	((ValaTypeRegisterFunctionClass *) klass)->get_gtype_value_table_peek_pointer_function_name = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_gtype_value_table_peek_pointer_function_name;
	((ValaTypeRegisterFunctionClass *) klass)->get_gtype_value_table_free_function_name = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_gtype_value_table_free_function_name;
	((ValaTypeRegisterFunctionClass *) klass)->get_gtype_value_table_copy_function_name = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_gtype_value_table_copy_function_name;
	((ValaTypeRegisterFunctionClass *) klass)->get_gtype_value_table_lcopy_value_function_name = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_gtype_value_table_lcopy_value_function_name;
	((ValaTypeRegisterFunctionClass *) klass)->get_gtype_value_table_collect_value_function_name = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_gtype_value_table_collect_value_function_name;
	((ValaTypeRegisterFunctionClass *) klass)->get_type_flags = (gchar* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_type_flags;
	((ValaTypeRegisterFunctionClass *) klass)->get_type_interface_init_declaration = (ValaCCodeFragment* (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_type_interface_init_declaration;
	((ValaTypeRegisterFunctionClass *) klass)->get_type_interface_init_statements = (void (*) (ValaTypeRegisterFunction *, ValaCodeContext*, ValaCCodeBlock*, gboolean)) vala_typeregister_function_real_get_type_interface_init_statements;
	((ValaTypeRegisterFunctionClass *) klass)->get_accessibility = (ValaSymbolAccessibility (*) (ValaTypeRegisterFunction *)) vala_typeregister_function_real_get_accessibility;
}


static void
vala_typeregister_function_instance_init (ValaTypeRegisterFunction * self)
{
	ValaCCodeFragment* _tmp0_;
	ValaCCodeFragment* _tmp1_;
	ValaCCodeFragment* _tmp2_;
	self->priv = vala_typeregister_function_get_instance_private (self);
	_tmp0_ = vala_ccode_fragment_new ();
	self->priv->source_declaration_fragment = _tmp0_;
	_tmp1_ = vala_ccode_fragment_new ();
	self->priv->declaration_fragment = _tmp1_;
	_tmp2_ = vala_ccode_fragment_new ();
	self->priv->definition_fragment = _tmp2_;
	self->ref_count = 1;
}


static void
vala_typeregister_function_finalize (ValaTypeRegisterFunction * obj)
{
	ValaTypeRegisterFunction * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_TYPE_TYPEREGISTER_FUNCTION, ValaTypeRegisterFunction);
	g_signal_handlers_destroy (self);
	_vala_ccode_node_unref0 (self->priv->source_declaration_fragment);
	_vala_ccode_node_unref0 (self->priv->declaration_fragment);
	_vala_ccode_node_unref0 (self->priv->definition_fragment);
}


/**
 * C function to register a type at runtime.
 */
GType
vala_typeregister_function_get_type (void)
{
	static volatile gsize vala_typeregister_function_type_id__volatile = 0;
	if (g_once_init_enter (&vala_typeregister_function_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { vala_value_typeregister_function_init, vala_value_typeregister_function_free_value, vala_value_typeregister_function_copy_value, vala_value_typeregister_function_peek_pointer, "p", vala_value_typeregister_function_collect_value, "p", vala_value_typeregister_function_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ValaTypeRegisterFunctionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_typeregister_function_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaTypeRegisterFunction), 0, (GInstanceInitFunc) vala_typeregister_function_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType vala_typeregister_function_type_id;
		vala_typeregister_function_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ValaTypeRegisterFunction", &g_define_type_info, &g_define_type_fundamental_info, G_TYPE_FLAG_ABSTRACT);
		ValaTypeRegisterFunction_private_offset = g_type_add_instance_private (vala_typeregister_function_type_id, sizeof (ValaTypeRegisterFunctionPrivate));
		g_once_init_leave (&vala_typeregister_function_type_id__volatile, vala_typeregister_function_type_id);
	}
	return vala_typeregister_function_type_id__volatile;
}


gpointer
vala_typeregister_function_ref (gpointer instance)
{
	ValaTypeRegisterFunction * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void
vala_typeregister_function_unref (gpointer instance)
{
	ValaTypeRegisterFunction * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



